<template>
  <div>
    <button>ihor-stryzhnov</button>
    <button>
      _hello
    </button>
    <button>
      _about-me
    </button>
    <button>
      _projects
    </button>
    <button>
      _contact-me
    </button>
  </div>
</template>
<script>
export default {}
</script>